# Generated by Django 4.2.7 on 2023-11-22 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0002_alter_drink_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='model/files/cover')),
            ],
        ),
        migrations.DeleteModel(
            name='Drink',
        ),
    ]
